# Generated by Django 2.2 on 2020-09-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app15', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('Webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app15.Webpage')),
            ],
        ),
        migrations.DeleteModel(
            name='AccesDetails',
        ),
    ]
