# Generated by Django 2.2 on 2020-09-08 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app15', '0002_auto_20200904_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
